USE dan;
SELECT * FROM dan.pro;
SELECT * FROM pro ORDER BY x ASC;
SELECT * FROM pro ORDER BY y1 DESC;
SELECT * FROM pro WHERE y2 > 8;
UPDATE pro SET y2 = 7.84 WHERE ï»¿=2;
SELECT COUNT(X) AS tx FROM pro;
SELECT max(y3) AS my3 FROM pro;
SELECT AVG(y2) AS avy2 FROM pro;
SELECT * FROM pro WHERE y2>8 and y3<8;
SELECT * FROM pro WHERE y2>9 or y3=8;
SELECT * FROM pro WHERE NOT y4>=7 ;
DELETE FROM pro WHERE ï»¿ = 11;
ROLLBACK;
COMMIT;
ALTER TABLE pro 
DROP COLUMN y4;
COMMIT;
SELECT * FROM dan.pro;
SELECT SUM(x),y1
FROM pro
GROUP BY Y1
HAVING SUM(x) > 10;
START TRANSACTION;
SAVEPOINT imp;
DELETE FROM pro WHERE ï»¿= 10;
SAVEPOINT im;
UPDATE pro SET y2 = 8.8 WHERE ï»¿ = 5;
SAVEPOINT I;
ROLLBACK TO im; 